"""Plugin: every CH:GmbH account must map to the Swiss KMU Kontenrahmen.

The statutory Bilanz/Erfolgsrechnung (OR Art. 959a/959b) are generated by
grouping accounts on the ``kmu:`` metadata of their ``open`` directive
(docs/plans/03). The mapping is data, not code — this plugin only guarantees
it can never silently drift: opening a ``*:CH:GmbH:*`` account without a
four-digit ``kmu:`` code is an error. US:LLC accounts are exempt (they map to
the CPA's US books instead).

Enable in main.bean:  plugin "quints.plugins.kmu"
(optionally with a marker: ``plugin "quints.plugins.kmu" ":CH:GmbH:"``)
"""

from __future__ import annotations

import re
from typing import Any, NamedTuple

from beancount.core import data

__plugins__ = ("validate_kmu",)

_ENTITY = ":CH:GmbH:"
_CODE = re.compile(r"^\d{4}$")


class KmuError(NamedTuple):
    source: dict
    message: str
    entry: data.Open


def validate_kmu(entries: data.Entries, _options_map: dict[str, Any], marker: str | None = None):
    marker = marker or _ENTITY
    errors = []
    for entry in entries:
        if not isinstance(entry, data.Open) or marker not in entry.account:
            continue
        code = (entry.meta or {}).get("kmu")
        if code is None:
            errors.append(
                KmuError(
                    entry.meta,
                    f"{entry.account} has no kmu: code — every CH:GmbH account "
                    f'must map to the KMU Kontenrahmen (e.g. kmu: "6570")',
                    entry,
                )
            )
        elif not isinstance(code, str) or not _CODE.match(code):
            errors.append(
                KmuError(
                    entry.meta,
                    f"{entry.account} has invalid kmu: {code!r} — expected a "
                    f'four-digit KMU account as a string, e.g. kmu: "6570"',
                    entry,
                )
            )
    return entries, errors
