"""quints configuration — the entity lives in ``quints.toml``, not in code.

Defaults are a neutral Swiss GmbH chart of accounts, so any repo following
the ``CH:GmbH`` namespacing works out of the box; everything entity-specific
(name, VAT registration, importer credentials/rules) comes from
``quints.toml`` — a stranger with their own beancount file and a
``quints.toml`` gets correct reports without touching this package.

Precedence: an explicit ``--config`` path > ``./quints.toml`` > built-in
defaults. VAT *rates* are deliberately not configurable — they are law and
live in :data:`quints.ledger.VAT_RATES`.

Modules take a ``cfg`` parameter (tests construct :class:`Config` inline) and
fall back to :func:`get`, the process-wide config the CLI resolves once.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, replace
from datetime import date as Date
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    import tomli as tomllib

DEFAULT_PATH = Path("quints.toml")

# The published documentation site. The invoice/issuer/customers JSON Schemas
# are hosted under <DOCS_URL>/schema/ (regenerated by `make docs`, sync-tested
# in CI); `quints init` writes yaml-language-server modelines pointing there.
DOCS_URL = "https://sealambda.github.io/quints"

# Legal form → account-name component (Assets:CH:<component>:…). The keys are
# the entity families the official KMU Kontenrahmen (veb.ch) prints Klasse-28
# variants for: juristische Personen (gmbh, ag) and Einzelunternehmen;
# Personengesellschaft (per-partner capital blocks) is not supported yet.
LEGAL_FORMS: dict[str, str] = {
    "gmbh": "GmbH",
    "ag": "AG",
    "einzelfirma": "Einzelfirma",
}


@dataclass(frozen=True)
class UbsImport:
    """[import.ubs] — MT940 statements for one CHF bank account."""

    account: str = "Assets:CH:GmbH:Current:UBS:CHF"
    iban: str | None = None  # required to identify statements
    currency: str = "CHF"
    rules: tuple[tuple[str, str, str], ...] = ()  # (payee regex, account, flag)


@dataclass(frozen=True)
class WiseImport:
    """[import.wise] — Wise balance statements, one account per currency."""

    accounts: tuple[tuple[str, str], ...] = (  # (currency, account)
        ("CHF", "Assets:CH:GmbH:Current:Wise:CHF"),
        ("EUR", "Assets:CH:GmbH:Current:Wise:EUR"),
        ("USD", "Assets:CH:GmbH:Current:Wise:USD"),
    )
    fees_account: str = "Expenses:CH:GmbH:BankFees:Wise"
    holder: str | None = None  # businessName filter (multi-profile tokens)
    rules: tuple[tuple[str, str, str], ...] = ()

    @property
    def account_map(self) -> dict[str, str]:
        return dict(self.accounts)


@dataclass(frozen=True)
class StripeImport:
    """[import.stripe] — Stripe balance transactions for one account."""

    accounts: tuple[tuple[str, str], ...] = (("EUR", "Assets:CH:GmbH:Current:Stripe:EUR"),)
    fees_account: str = "Expenses:CH:GmbH:BankFees:Stripe"
    tax_account: str = "Assets:CH:GmbH:Tax:InputVAT"  # VAT within Stripe's own fees
    account_id: str | None = None  # required: acct_… this key must belong to
    rules: tuple[tuple[str, str, str], ...] = ()

    @property
    def account_map(self) -> dict[str, str]:
        return dict(self.accounts)


@dataclass(frozen=True)
class YapealImport:
    """[import.yapeal] — Yapeal CSV statements for one CHF bank account."""

    account: str = "Assets:CH:GmbH:Current:Bank:CHF"
    iban: str | None = None  # optional — matched against file content
    currency: str = "CHF"
    rules: tuple[tuple[str, str, str], ...] = ()


@dataclass(frozen=True)
class Config:
    # [entity]
    entity_name: str = "Example GmbH"
    legal_form: str = "gmbh"  # key into LEGAL_FORMS; picks the Klasse-28 equity variant
    vat_method: str = "effective"  # "saldo" would need a different Form-310 mapping
    vat_registered_since: Date | None = None
    operating_currency: str = "CHF"
    # [ledger]
    ledger_main: Path = Path("main.bean")
    ledger_prices: Path = Path("prices.bean")
    # [accounts]
    input_vat: str = "Assets:CH:GmbH:Tax:InputVAT"
    output_vat: str = "Liabilities:CH:GmbH:Tax:OutputVAT"
    bezugsteuer: str = "Liabilities:CH:GmbH:Tax:Bezugsteuer"
    payable_vat: str = "Liabilities:CH:GmbH:Tax:PayableVAT"
    income_prefix: str = "Income:CH:GmbH"
    export_marker: str = ":Export"
    entity_marker: str = ":CH:GmbH:"
    fx_gain: str = "Income:CH:GmbH:FX:CurrencyGain"
    fx_loss: str = "Expenses:CH:GmbH:FX:CurrencyLoss"
    receivable: str = "Assets:CH:GmbH:Receivable:Trade"
    rounding_income: str = "Income:CH:GmbH:Rounding"
    income_domestic: str = "Income:CH:GmbH:Consulting:External:Domestic"
    income_export: str = "Income:CH:GmbH:Consulting:External:Export"
    # [prices]
    prices_source: str = "beanprice_bazg"  # beanprice source module for `prices sync`
    prices_currencies: tuple[str, ...] = ("USD", "EUR")  # priced against operating_currency
    prices_tickers: tuple[tuple[str, str], ...] = ()  # currency -> source ticker, when they differ
    # [report]
    report_language: str = "en"
    # [import.*] — statement importers (plan 2); None = not configured
    import_ubs: UbsImport | None = None
    import_yapeal: YapealImport | None = None
    import_wise: WiseImport | None = None
    import_stripe: StripeImport | None = None


def _rules(section: dict[str, object]) -> tuple[tuple[str, str, str], ...]:
    rules = section.get("rules")
    if not isinstance(rules, list):
        return ()
    return tuple((r[0], r[1], r[2]) for r in rules)


def _accounts_map(
    section: dict[str, object], default: tuple[tuple[str, str], ...]
) -> tuple[tuple[str, str], ...]:
    accounts = section.get("accounts")
    if not isinstance(accounts, dict):
        return default
    return tuple(sorted(accounts.items()))


def _import_sections(raw: dict[str, object]) -> dict[str, object]:
    imports = raw.get("import")
    if not isinstance(imports, dict):
        return {}
    updates: dict[str, object] = {}
    ubs = imports.get("ubs")
    if isinstance(ubs, dict):
        updates["import_ubs"] = UbsImport(
            account=ubs.get("account", UbsImport.account),
            iban=ubs.get("iban"),
            currency=ubs.get("currency", UbsImport.currency),
            rules=_rules(ubs),
        )
    yapeal = imports.get("yapeal")
    if isinstance(yapeal, dict):
        updates["import_yapeal"] = YapealImport(
            account=yapeal.get("account", YapealImport.account),
            iban=yapeal.get("iban"),
            currency=yapeal.get("currency", YapealImport.currency),
            rules=_rules(yapeal),
        )
    wise = imports.get("wise")
    if isinstance(wise, dict):
        updates["import_wise"] = WiseImport(
            accounts=_accounts_map(wise, WiseImport.accounts),
            fees_account=wise.get("fees_account", WiseImport.fees_account),
            holder=wise.get("holder"),
            rules=_rules(wise),
        )
    stripe = imports.get("stripe")
    if isinstance(stripe, dict):
        updates["import_stripe"] = StripeImport(
            accounts=_accounts_map(stripe, StripeImport.accounts),
            fees_account=stripe.get("fees_account", StripeImport.fees_account),
            tax_account=stripe.get("tax_account", StripeImport.tax_account),
            account_id=stripe.get("account_id"),
            rules=_rules(stripe),
        )
    return updates


def _from_mapping(raw: dict[str, object]) -> Config:
    def section(key: str) -> dict[str, object]:
        value = raw.get(key)
        return value if isinstance(value, dict) else {}

    entity = section("entity")
    ledger_ = section("ledger")
    accounts = section("accounts")
    report = section("report")
    cfg = Config()
    updates: dict[str, object] = {}

    def take(section: dict[str, object], key: str, field: str) -> None:
        if key in section:
            updates[field] = section[key]

    take(entity, "name", "entity_name")
    take(entity, "legal_form", "legal_form")
    take(entity, "vat_method", "vat_method")
    take(entity, "vat_registered_since", "vat_registered_since")
    take(entity, "operating_currency", "operating_currency")
    if "main" in ledger_:
        updates["ledger_main"] = Path(str(ledger_["main"]))
    if "prices" in ledger_:
        updates["ledger_prices"] = Path(str(ledger_["prices"]))
    for key in (
        "input_vat",
        "output_vat",
        "bezugsteuer",
        "payable_vat",
        "income_prefix",
        "export_marker",
        "entity_marker",
        "fx_gain",
        "fx_loss",
        "receivable",
        "rounding_income",
        "income_domestic",
        "income_export",
    ):
        take(accounts, key, key)
    prices_ = section("prices")
    take(prices_, "source", "prices_source")
    if "currencies" in prices_:
        currencies = prices_["currencies"]
        if isinstance(currencies, list):
            updates["prices_currencies"] = tuple(str(c) for c in currencies)
    tickers = prices_.get("tickers")
    if isinstance(tickers, dict):
        updates["prices_tickers"] = tuple(sorted((str(k), str(v)) for k, v in tickers.items()))
    take(report, "language", "report_language")
    updates.update(_import_sections(raw))
    return replace(cfg, **updates)


def load(path: Path | None = None) -> Config:
    """Load ``path``, or ``./quints.toml`` if present, else defaults."""
    if path is None:
        path = DEFAULT_PATH if DEFAULT_PATH.exists() else None
    if path is None:
        return Config()
    with open(path, "rb") as f:
        return _from_mapping(tomllib.load(f))


_current: Config | None = None
_path: Path | None = None


def set_path(path: Path | None) -> None:
    """CLI hook: remember --config and invalidate the cached config."""
    global _path, _current
    _path = path
    _current = None


def get() -> Config:
    """The process-wide config (cached; honors a previous :func:`set_path`)."""
    global _current
    if _current is None:
        _current = load(_path)
    return _current
