"""quints configuration — the entity lives in ``quints.toml``, not in code.

Defaults are a neutral Swiss GmbH chart of accounts, so any repo following
the ``CH:GmbH`` namespacing works out of the box; everything entity-specific
(name, VAT registration, importer credentials/rules) comes from
``quints.toml`` — a stranger with their own beancount file and a
``quints.toml`` gets correct reports without touching this package.

Precedence: an explicit ``--config`` path > ``./quints.toml`` > built-in
defaults. VAT *rates* are deliberately not configurable — they are law and
live in :data:`quints.ledger.VAT_RATES`.

Modules take a ``cfg`` parameter (tests construct :class:`Config` inline) and
fall back to :func:`get`, the process-wide config the CLI resolves once.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, replace
from datetime import date as Date
from decimal import Decimal, InvalidOperation
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    import tomli as tomllib

DEFAULT_PATH = Path("quints.toml")

# The published documentation site. The invoice/issuer/customers JSON Schemas
# are hosted under <DOCS_URL>/schema/ (regenerated by `make docs`, sync-tested
# in CI); `quints init` writes yaml-language-server modelines pointing there.
DOCS_URL = "https://sealambda.github.io/quints"

# Legal form → account-name component (Assets:CH:<component>:…). The keys are
# the entity families the official KMU Kontenrahmen (veb.ch) prints Klasse-28
# variants for: juristische Personen (gmbh, ag) and Einzelunternehmen;
# Personengesellschaft (per-partner capital blocks) is not supported yet.
LEGAL_FORMS: dict[str, str] = {
    "gmbh": "GmbH",
    "ag": "AG",
    "einzelfirma": "Einzelfirma",
}

# VAT methods and their default filing period. Under the Saldosteuersatz
# method the Steuerperiode splits into two Abrechnungsperioden (Art. 35 Abs. 1
# Bst. b MWSTG); the effective method files quarterly. Since 2025 both may file
# annually on request (Art. 35a MWSTG) — set ``[vat] period = "year"``.
VAT_METHODS: dict[str, str] = {"effective": "quarter", "saldo": "half-year"}
PERIOD_KINDS = ("quarter", "half-year", "year")


class ConfigError(ValueError):
    """quints.toml says something that cannot be true."""


@dataclass(frozen=True)
class SaldoRate:
    """One Saldosteuersatz the ESTV granted, and the turnover it applies to.

    ``rate`` is a fraction (6.2 % → ``Decimal("0.062")``) and must be one of
    the rates the ordinance lists (:data:`quints.ledger.SALDO_RATES`); which
    one a business gets is the ESTV's decision, hence config. ``marker`` is an
    income sub-account marker like the Ziffer markers; the first entry with no
    marker is the default rate. ``label`` is how ``mwst: "sss=<label>"`` names
    it, and defaults to the per-cent spelling ("6.2").
    """

    rate: Decimal
    marker: str = ""
    label: str = ""

    @property
    def name(self) -> str:
        """How ``mwst: "sss=<name>"`` spells it — per cent, as the ordinance prints it."""
        return self.label or str((self.rate * 100).quantize(Decimal("0.1")))


@dataclass(frozen=True)
class UbsImport:
    """[import.ubs] — MT940 statements for one CHF bank account."""

    account: str = "Assets:CH:GmbH:Current:UBS:CHF"
    iban: str | None = None  # required to identify statements
    currency: str = "CHF"
    rules: tuple[tuple[str, str, str], ...] = ()  # (payee regex, account, flag)


@dataclass(frozen=True)
class WiseImport:
    """[import.wise] — Wise balance statements, one account per currency."""

    accounts: tuple[tuple[str, str], ...] = (  # (currency, account)
        ("CHF", "Assets:CH:GmbH:Current:Wise:CHF"),
        ("EUR", "Assets:CH:GmbH:Current:Wise:EUR"),
        ("USD", "Assets:CH:GmbH:Current:Wise:USD"),
    )
    fees_account: str = "Expenses:CH:GmbH:BankFees:Wise"
    holder: str | None = None  # businessName filter (multi-profile tokens)
    rules: tuple[tuple[str, str, str], ...] = ()

    @property
    def account_map(self) -> dict[str, str]:
        return dict(self.accounts)


@dataclass(frozen=True)
class StripeImport:
    """[import.stripe] — Stripe balance transactions for one account."""

    accounts: tuple[tuple[str, str], ...] = (("EUR", "Assets:CH:GmbH:Current:Stripe:EUR"),)
    fees_account: str = "Expenses:CH:GmbH:BankFees:Stripe"
    tax_account: str = "Assets:CH:GmbH:Tax:InputVAT"  # VAT within Stripe's own fees
    account_id: str | None = None  # required: acct_… this key must belong to
    rules: tuple[tuple[str, str, str], ...] = ()

    @property
    def account_map(self) -> dict[str, str]:
        return dict(self.accounts)


@dataclass(frozen=True)
class YapealImport:
    """[import.yapeal] — Yapeal CSV statements for one CHF bank account."""

    account: str = "Assets:CH:GmbH:Current:Bank:CHF"
    iban: str | None = None  # optional — matched against file content
    currency: str = "CHF"
    rules: tuple[tuple[str, str, str], ...] = ()


@dataclass(frozen=True)
class Config:
    """The entity. ``period_kind`` is the only derived value."""

    # [entity]
    entity_name: str = "Example GmbH"
    legal_form: str = "gmbh"  # key into LEGAL_FORMS; picks the Klasse-28 equity variant
    vat_method: str = "effective"  # key into VAT_METHODS: effective | saldo
    vat_registered_since: Date | None = None
    operating_currency: str = "CHF"
    # [ledger]
    ledger_main: Path = Path("main.bean")
    ledger_prices: Path = Path("prices.bean")
    # [accounts]
    input_vat: str = "Assets:CH:GmbH:Tax:InputVAT"
    output_vat: str = "Liabilities:CH:GmbH:Tax:OutputVAT"
    bezugsteuer: str = "Liabilities:CH:GmbH:Tax:Bezugsteuer"
    payable_vat: str = "Liabilities:CH:GmbH:Tax:PayableVAT"
    income_prefix: str = "Income:CH:GmbH"
    # Income sub-account markers routing turnover to a Form-310 Ziffer. The
    # longest/most specific is tested first, so ":ExportGoods" wins over
    # ":Export". An empty string disables a marker.
    export_marker: str = ":Export"  # Ziffer 221 — Ort der Leistung im Ausland
    export_goods_marker: str = ":ExportGoods"  # Ziffer 220 — Exporte, Art. 23
    exempt_marker: str = ":Exempt"  # Ziffer 230 — ausgenommen, Art. 21
    optioned_marker: str = ":Optioned"  # Ziffer 205 memo — Option, Art. 22
    # Rate-class markers (Art. 25 MWSTG); unmarked taxable turnover is standard.
    reduced_marker: str = ":Reduced"  # 2.6 % → Ziffer 313
    lodging_marker: str = ":Lodging"  # 3.8 % Beherbergung → Ziffer 343
    entity_marker: str = ":CH:GmbH:"
    fx_gain: str = "Income:CH:GmbH:FX:CurrencyGain"
    fx_loss: str = "Expenses:CH:GmbH:FX:CurrencyLoss"
    receivable: str = "Assets:CH:GmbH:Receivable:Trade"
    payable: str = "Liabilities:CH:GmbH:Payable:Trade"
    rounding_income: str = "Income:CH:GmbH:Rounding"
    income_domestic: str = "Income:CH:GmbH:Consulting:External:Domestic"
    income_export: str = "Income:CH:GmbH:Consulting:External:Export"
    # Saldosteuersatz method only. The difference between the statutory VAT
    # invoiced and the SSS owed lands in `saldo_difference` at settlement;
    # Bezugsteuer is a cost, not a deduction, so it lands in
    # `bezugsteuer_expense`. Both are excluded from the return by identity.
    saldo_difference: str = "Income:CH:GmbH:VAT:SaldoDifference"
    bezugsteuer_expense: str = "Expenses:CH:GmbH:Tax:Bezugsteuer"
    # [payables]
    payables_default_terms_days: int = 30  # due date when a bill carries no `due:`
    # [prices]
    prices_source: str = "beanprice_bazg"  # beanprice source module for `prices sync`
    prices_currencies: tuple[str, ...] = ("USD", "EUR")  # priced against operating_currency
    prices_tickers: tuple[tuple[str, str], ...] = ()  # currency -> source ticker, when they differ
    # [vat]
    vat_period: str = ""  # "" = the method's default (see VAT_METHODS)
    saldo: tuple[SaldoRate, ...] = ()  # the granted Saldosteuersätze
    # [report]
    report_language: str = "en"
    # [import.*] — statement importers (plan 2); None = not configured
    import_ubs: UbsImport | None = None
    import_yapeal: YapealImport | None = None
    import_wise: WiseImport | None = None
    import_stripe: StripeImport | None = None

    @property
    def period_kind(self) -> str:
        """The VAT filing period: explicit, else the method's statutory default."""
        return self.vat_period or VAT_METHODS.get(self.vat_method, "quarter")

    @property
    def saldo_default(self) -> SaldoRate | None:
        """The rate unmarked turnover falls to — the first entry without a marker."""
        for granted in self.saldo:
            if not granted.marker:
                return granted
        return self.saldo[0] if self.saldo else None


def _rules(section: dict[str, object]) -> tuple[tuple[str, str, str], ...]:
    rules = section.get("rules")
    if not isinstance(rules, list):
        return ()
    return tuple((r[0], r[1], r[2]) for r in rules)


def _accounts_map(
    section: dict[str, object], default: tuple[tuple[str, str], ...]
) -> tuple[tuple[str, str], ...]:
    accounts = section.get("accounts")
    if not isinstance(accounts, dict):
        return default
    return tuple(sorted(accounts.items()))


def _import_sections(raw: dict[str, object]) -> dict[str, object]:
    imports = raw.get("import")
    if not isinstance(imports, dict):
        return {}
    updates: dict[str, object] = {}
    ubs = imports.get("ubs")
    if isinstance(ubs, dict):
        updates["import_ubs"] = UbsImport(
            account=ubs.get("account", UbsImport.account),
            iban=ubs.get("iban"),
            currency=ubs.get("currency", UbsImport.currency),
            rules=_rules(ubs),
        )
    yapeal = imports.get("yapeal")
    if isinstance(yapeal, dict):
        updates["import_yapeal"] = YapealImport(
            account=yapeal.get("account", YapealImport.account),
            iban=yapeal.get("iban"),
            currency=yapeal.get("currency", YapealImport.currency),
            rules=_rules(yapeal),
        )
    wise = imports.get("wise")
    if isinstance(wise, dict):
        updates["import_wise"] = WiseImport(
            accounts=_accounts_map(wise, WiseImport.accounts),
            fees_account=wise.get("fees_account", WiseImport.fees_account),
            holder=wise.get("holder"),
            rules=_rules(wise),
        )
    stripe = imports.get("stripe")
    if isinstance(stripe, dict):
        updates["import_stripe"] = StripeImport(
            accounts=_accounts_map(stripe, StripeImport.accounts),
            fees_account=stripe.get("fees_account", StripeImport.fees_account),
            tax_account=stripe.get("tax_account", StripeImport.tax_account),
            account_id=stripe.get("account_id"),
            rules=_rules(stripe),
        )
    return updates


def _from_mapping(raw: dict[str, object]) -> Config:
    def section(key: str) -> dict[str, object]:
        value = raw.get(key)
        return value if isinstance(value, dict) else {}

    entity = section("entity")
    ledger_ = section("ledger")
    accounts = section("accounts")
    report = section("report")
    cfg = Config()
    updates: dict[str, object] = {}

    def take(section: dict[str, object], key: str, field: str) -> None:
        if key in section:
            updates[field] = section[key]

    take(entity, "name", "entity_name")
    take(entity, "legal_form", "legal_form")
    take(entity, "vat_method", "vat_method")
    take(entity, "vat_registered_since", "vat_registered_since")
    take(entity, "operating_currency", "operating_currency")
    if "main" in ledger_:
        updates["ledger_main"] = Path(str(ledger_["main"]))
    if "prices" in ledger_:
        updates["ledger_prices"] = Path(str(ledger_["prices"]))
    for key in (
        "input_vat",
        "output_vat",
        "bezugsteuer",
        "payable_vat",
        "income_prefix",
        "export_marker",
        "export_goods_marker",
        "exempt_marker",
        "optioned_marker",
        "reduced_marker",
        "lodging_marker",
        "entity_marker",
        "fx_gain",
        "fx_loss",
        "receivable",
        "payable",
        "rounding_income",
        "income_domestic",
        "income_export",
        "saldo_difference",
        "bezugsteuer_expense",
    ):
        take(accounts, key, key)
    payables_ = section("payables")
    take(payables_, "default_terms_days", "payables_default_terms_days")
    prices_ = section("prices")
    take(prices_, "source", "prices_source")
    if "currencies" in prices_:
        currencies = prices_["currencies"]
        if isinstance(currencies, list):
            updates["prices_currencies"] = tuple(str(c) for c in currencies)
    tickers = prices_.get("tickers")
    if isinstance(tickers, dict):
        updates["prices_tickers"] = tuple(sorted((str(k), str(v)) for k, v in tickers.items()))
    take(report, "language", "report_language")
    vat = section("vat")
    take(vat, "period", "vat_period")
    if "saldo" in vat:
        updates["saldo"] = _saldo_rates(vat["saldo"])
    updates.update(_import_sections(raw))
    return replace(cfg, **updates)


def _saldo_rates(raw: object) -> tuple[SaldoRate, ...]:
    """Parse ``[[vat.saldo]]`` — rates are given in per cent, as the ESTV grants them."""
    if not isinstance(raw, list):
        raise ConfigError("[vat.saldo] must be a list of tables, e.g. [[vat.saldo]] rate = 6.2")
    rates: list[SaldoRate] = []
    for entry in raw:
        if not isinstance(entry, dict):
            raise ConfigError("each [[vat.saldo]] entry must be a table with a `rate`")
        if "rate" not in entry:
            raise ConfigError("a [[vat.saldo]] entry has no `rate`")
        try:
            percent = Decimal(str(entry["rate"]))
        except InvalidOperation:
            raise ConfigError(f"[[vat.saldo]] rate {entry['rate']!r} is not a number") from None
        rates.append(
            SaldoRate(
                rate=percent / 100,
                marker=str(entry.get("marker", "")),
                label=str(entry.get("label", "")),
            )
        )
    return tuple(rates)


def validate(cfg: Config) -> Config:
    """Reject a quints.toml that cannot produce a correct return.

    VAT law is not configurable: the method, the filing period and the
    permitted Saldosteuersätze are all closed sets, so a typo has to fail here
    rather than quietly produce a wrong Ziffer.
    """
    # Imported here: `ledger` is a sibling in the foundation layer and holds
    # the statutory tables, but nothing else in config needs it.
    from . import ledger

    if cfg.vat_method not in VAT_METHODS:
        raise ConfigError(
            f"[entity] vat_method {cfg.vat_method!r} is unknown — "
            f"supported: {', '.join(VAT_METHODS)}"
        )
    if cfg.vat_period and cfg.vat_period not in PERIOD_KINDS:
        raise ConfigError(
            f"[vat] period {cfg.vat_period!r} is unknown — supported: {', '.join(PERIOD_KINDS)}"
        )
    if cfg.vat_method == "saldo" and not cfg.saldo:
        raise ConfigError(
            '[entity] vat_method = "saldo" needs the rates the ESTV granted you, e.g.\n'
            "           [[vat.saldo]]\n           rate = 6.2"
        )
    if cfg.vat_method != "saldo" and cfg.saldo:
        raise ConfigError('[vat.saldo] is set but [entity] vat_method is not "saldo"')
    for granted in cfg.saldo:
        if not ledger.is_saldo_rate(granted.rate):
            permitted = ", ".join(f"{r * 100:g}" for r in ledger.SALDO_RATES[0][1])
            raise ConfigError(
                f"[[vat.saldo]] rate {granted.rate * 100:g} is not a Saldosteuersatz — "
                f"the ESTV grants one of {permitted} (SR 641.202.62)"
            )
    labels = [g.name for g in cfg.saldo]
    if len(set(labels)) != len(labels):
        raise ConfigError(f"[[vat.saldo]] has duplicate rates/labels: {', '.join(labels)}")
    return cfg


def load(path: Path | None = None) -> Config:
    """Load ``path``, or ``./quints.toml`` if present, else defaults."""
    if path is None:
        path = DEFAULT_PATH if DEFAULT_PATH.exists() else None
    if path is None:
        return validate(Config())
    with open(path, "rb") as f:
        return validate(_from_mapping(tomllib.load(f)))


_current: Config | None = None
_path: Path | None = None


def set_path(path: Path | None) -> None:
    """CLI hook: remember --config and invalidate the cached config."""
    global _path, _current
    _path = path
    _current = None


def get() -> Config:
    """The process-wide config (cached; honors a previous :func:`set_path`)."""
    global _current
    if _current is None:
        _current = load(_path)
    return _current
